name: 'Submodule Checkout'
description: 'Checkout the submodules of the repositories'
inputs:
  ssh-key:
    description: 'Optional SSH key'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Checkout submodules'
      using: node16
      run: |
        if [[ -n "${{ inputs.ssh-key }}" ]]; then
          mkdir -p ~/.ssh/
          echo "${{ inputs.ssh-key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        fi

        git submodule init
        git submodule update
